management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true


spring:
  mvc:
    favicon.enabled: false
  security:
    basic:
      enabled: false
    oauth2:
      client:
        registration:
          facebook:
            clientId: 1247520388755362
            clientSecret: 702b1ac579a1e9773c41839f8fb71944
          github:
            clientId: 3a187a7cf91ebbf5d907
            clientSecret: b7569f7c37c6d94faa978899eca646976e1cef40
          google:
            clientId: 928373256663-90j4tg9d7ihsaed1l053bq2hbjtnll32.apps.googleusercontent.com
            clientSecret: mTrpMgyLQDPp2RscMf3Dsj0T
server:
  error:
    whitelabel.enabled: false
  port: 9000
  servlet:
    contextPath: /

logging:
  level:
    root: WARN
    org.springframework.security: WARN

app:
  auth:
    clientId: foo
    scopes:
    - openid
    grantTypes:
    - implicit
    redirectUris:
    - "http://localhost:3000/implicit/callback"
    - "http://localhost:3000/silent-renew"
    accessTokenValiditySeconds: 900
    loginPage: "/oauth2/authorization/google"
  keystore:
    file: keystore.jks
    name: keystore
    password: password

